### PR TITLE
Reynolds v. Sims

### PR DESCRIPTION
**Pull request by zackmdavis**
@cookjw review plz

### CODE REVIEW

**Comment by zackmdavis** [comment]
Like, do you think the "setting the current user as an attribute on each post so that `render` can still be a model (mixin) method" hack is OK, or should we search for a better way to do things? If it is okay, is there some way to make it less verbose and easy-to-forget-on-a-new-view&mdash;I guess that could go in our `scored_context` helper, but that mechanism is itself somewhat questionable (and would probably mean the end of our [brief](https://github.com/zackmdavis/Finetooth/blob/8a1f3790/core/views/views.py#L76) consideration of class-based views, for better or for worse).

**Comment by cookjw** [comment]
Why is the `scored_context` mechanism questionable? Also,  I don't (yet?) understand the point of class-based views.

**Comment by zackmdavis** [comment]
Well, I must have been confused or forgetful when I wrote the previous comment; `scored_context` is OK. (I mean, I don't remember seeing such a "pass the entire prospective context dictionary to a function before actually giving it to render" pattern before, but that doesn't make it *illegitimate*.)

What is *very* questionable, on the other hand (and what I may have been trying to think of in the previous comment), is the `@paginated_view`/`paginated_context` hack&mdash;it's awfully DAMP ("duplicated areas of my program") to have to decorate a view *and* call a function (`paginated_context`) on the context-to-be in order for some piece of functionality to work! Whereas even though I don't really *like* [class-based views](https://docs.djangoproject.com/en/1.8/topics/class-based-views/intro/#the-relationship-and-history-of-generic-views-class-based-views-and-class-based-generic-views) (brittle and opaque magic is the worst kind; I mostly used it for the monthly archives view to cement my status as a true Djangonaut), I was surprised at [how much code](https://github.com/zackmdavis/Finetooth/blob/master/core/views/view_utils.py#L24-67) it took for me to implement pagination myself even with the [`Paginator`](https://docs.djangoproject.com/en/1.8/topics/pagination/#django.core.paginator.Paginator), and `ListView` gives you that functionality nearly for free ...

Anyway, I have some ideas about how to improve `@paginated_context` and `scored_context`, so I'll probably end up doing that and convert the archives view away from `ListView`.

**Comment by cookjw** [comment]
OK, since the overlapping-vote-prevention mechanism appears to work, I'm just going to go ahead and merge this on the assumption that the improvements to which you allude can be made in a future *version* over which we'll have some degree of *control*...

**Comment by zackmdavis** [comment]
:shipit:

**Pull request merged**
